---
- hosts: webserver
  become: yes
  gather_facts: no
  tasks:

  #######################################################################
  ## Installing LampStack and php-mysql bindings
  #######################################################################
  - name: "Install Lamstack with php-mysql bindings"
    yum: name="{{ item }}" state=present
    with_items:
    - httpd
    
  - name: "Restart webserver"
    service: name=httpd state=restarted

  - name: "Copy webfiles"
    copy: src=./index.html dest=/var/www/html

